FROM python:3.9-slim

WORKDIR /app

COPY ./src /app/src
COPY ./requirements.txt /app/requirements.txt

RUN pip install --no-cache-dir -r requirements.txt

COPY ./main_model.py /app/model_main.py

CMD ["python", "model_main.py"]
