services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongo/init.js:/docker-entrypoint-initdb.d/init.js:ro

  api:
    build:
      context: .
      dockerfile: api/Dockerfile.api  # Chemin vers le Dockerfile
    container_name: api
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    volumes:
      - ./artifacts:/app/artifacts

volumes:
  mongo-data:

