services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongo/init.js:/docker-entrypoint-initdb.d/init.js:ro

  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper

  ml_service:
    build: ./ml_service
    container_name: ml_service
    depends_on:
      - kafka
      - mongo
    volumes:
      - ./data:/data  # Partage du modèle entraîné

  fastapi:
    build: ./fastapi
    container_name: fastapi
    ports:
      - "8000:8000"
    depends_on:
      - ml_service
    volumes:
      - ./data:/data  # Accès au modèle Doc2Vec

