FROM python:3.9-slim

WORKDIR /app

# Copiez tout le contenu du répertoire src dans le conteneur
COPY . /app/api
COPY ../database /app/database
COPY ../model /app/model

# Copiez le fichier requirements.txt à la racine du projet
COPY requirements.txt /app/requirements.txt

# Installez les dépendances
RUN pip install --no-cache-dir -r requirements.txt

# Commande pour exécuter l'application
CMD ["uvicorn", "src.api.api:app", "--host", "0.0.0.0", "--port", "8000"]


